@startuml
' Configuración de colores estilo docente
skinparam usecase {
    BackgroundColor #1FA1F1
    BorderColor #1FA1F1
    FontColor white
    FontSize 14
}
skinparam actor {
    BorderColor #1FA1F1
    FontColor #2E4D68
    BackgroundColor white
}
skinparam ArrowColor #1FA1F1
skinparam package {
    BorderColor #1FA1F1
    FontColor #1FA1F1
}

actor "Administrador" as admin
actor "Director" as dir

rectangle "SYS PASANTIAS" {
    usecase "🔍\nValidar registros\nduplicados" as uc_validar
    usecase "🔑\nActualizar niveles\nde acceso (Roles)" as uc_roles
    usecase "<b>CU03</b>\nGestionar usuarios" as uc_main
    usecase "❌\nMostrar error\nde duplicado" as uc_error
}

admin -[#1FA1F1]-> uc_main : Accede
dir -[#1FA1F1]-> uc_main : Accede

uc_main .up.> uc_validar : <<include>>
uc_main .up.> uc_roles : <<include>>
uc_error .down.> uc_main : <<extend>>
@endum